formatter: "markdown table"
version: "0.17.0"

content: |-
  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: inject

sections:
  hide: [providers]

output-values:
  enabled: false
  from: ""

sort:
  enabled: false

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
